### ISSUE TITLE
Seem didnt work?

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/NXSBinEditor#1]
i didnt compile this dll, but update from sacana wrapper
when i try to extract the script it just gave me an empty txt
game: https://vndb.org/v16338
script sample: [RAW.ZIP](https://drive.google.com/open?id=1L25eGrOrunT-K-2axQNZ3DkRJ_8mdf_b)

**Comment by marcussacana** [comment]
Thx, this format isn't the same of my base game, i will start work in a update.
 If you have more scripts, upload to me.

**Comment by marcussacana** [comment]
Okay, Updated.
Update the plugin and try again, Test if the game run too...
 if works, close the issue, if not.. huh, only with specifc-game tool, I don't work with disasm tools.

**Comment by 0xh3LL0** [comment]
updated, and it works, thanks!
<a href="https://imgur.com/8eO06ga"><img src="https://i.imgur.com/8eO06ga.png" title="source: imgur.com" /></a>
