### ISSUE TITLE
empty txt with the game Majikoi A4

### ISSUE THREAD

**Issue by Darkau** [marcussacana/NXSBinEditor#2]
Empty txt, ( and some bin files didn't work)
[__global.txt](https://github.com/marcussacana/NXSBinEditor/files/1733869/__global.txt)
[eventmode.txt](https://github.com/marcussacana/NXSBinEditor/files/1733870/eventmode.txt)
[j1_0600_0.txt](https://github.com/marcussacana/NXSBinEditor/files/1733871/j1_0600_0.txt)
[j1_0624_0.txt](https://github.com/marcussacana/NXSBinEditor/files/1733872/j1_0624_0.txt)
[j1_0625_0.txt](https://github.com/marcussacana/NXSBinEditor/files/1733873/j1_0625_0.txt)
[j1_0626_0.txt](https://github.com/marcussacana/NXSBinEditor/files/1733875/j1_0626_0.txt)
[j1_0629_0.txt](https://github.com/marcussacana/NXSBinEditor/files/1733876/j1_0629_0.txt)
...

I can send more if required
Thank you

**Comment by marcussacana** [comment]
the .txt empty isn't required, plz send the original script

**Comment by Darkau** [comment]
.bin files aren't supported here. Here is a link with the script in bin format:

http://www.mediafire.com/file/w3oq2s1qy2pmqb2/Script4~.pac.zip

**Comment by marcussacana** [comment]
Fixed...
Download new build of the sacanawrapper and Install the "Nexas Bin String Editor (v3)"
![https://vgy.me/6tuItv.png](https://vgy.me/6tuItv.png)

If have any problem to run with the game plz say
